# pull latest python
image: python:latest

services:
  - postgres

# cache pip
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  POSTGRES_DB: test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST: postgres

# cache stuff
cache:
  paths:
    - .cache/pip
    - venv/

database:
  image: postgres
  script:
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT 'OK' AS status;"

test:
  script:
    - pip install -r requirements.txt virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - python test.py
