image: python:latest

services:
  - postgres:latest

variables:
  POSTGRES_DB: xaiecon_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - /usr/local/lib/

stages:
  - test

test:
    script:
    - pip3 install -r requirements.txt
    - python3 test.py
